version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "api"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "front"
    schedule:
      interval: "weekly"
