// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Project struct {
	ID        pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
}

type ProjectBot struct {
	ID        pgtype.UUID
	ProjectID pgtype.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
}

type ProjectBotPath struct {
	ID           pgtype.UUID
	ProjectBotID pgtype.UUID
	Path         string
	Allowed      bool
	CreatedAt    pgtype.Timestamptz
}
