// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: pb/robots.proto

package robots

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_pb_robots_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pb_robots_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pb_robots_proto_rawDescGZIP(), []int{0}
}

type ProjectModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectModel) Reset() {
	*x = ProjectModel{}
	mi := &file_pb_robots_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectModel) ProtoMessage() {}

func (x *ProjectModel) ProtoReflect() protoreflect.Message {
	mi := &file_pb_robots_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectModel.ProtoReflect.Descriptor instead.
func (*ProjectModel) Descriptor() ([]byte, []int) {
	return file_pb_robots_proto_rawDescGZIP(), []int{1}
}

func (x *ProjectModel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProjectModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProjectModel) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ProjectGetAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectGetAllRequest) Reset() {
	*x = ProjectGetAllRequest{}
	mi := &file_pb_robots_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectGetAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectGetAllRequest) ProtoMessage() {}

func (x *ProjectGetAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_robots_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectGetAllRequest.ProtoReflect.Descriptor instead.
func (*ProjectGetAllRequest) Descriptor() ([]byte, []int) {
	return file_pb_robots_proto_rawDescGZIP(), []int{2}
}

type ProjectGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectGetRequest) Reset() {
	*x = ProjectGetRequest{}
	mi := &file_pb_robots_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectGetRequest) ProtoMessage() {}

func (x *ProjectGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_robots_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectGetRequest.ProtoReflect.Descriptor instead.
func (*ProjectGetRequest) Descriptor() ([]byte, []int) {
	return file_pb_robots_proto_rawDescGZIP(), []int{3}
}

func (x *ProjectGetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ProjectCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectCreateRequest) Reset() {
	*x = ProjectCreateRequest{}
	mi := &file_pb_robots_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectCreateRequest) ProtoMessage() {}

func (x *ProjectCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_robots_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectCreateRequest.ProtoReflect.Descriptor instead.
func (*ProjectCreateRequest) Descriptor() ([]byte, []int) {
	return file_pb_robots_proto_rawDescGZIP(), []int{4}
}

func (x *ProjectCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ProjectDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectDeleteRequest) Reset() {
	*x = ProjectDeleteRequest{}
	mi := &file_pb_robots_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectDeleteRequest) ProtoMessage() {}

func (x *ProjectDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_robots_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectDeleteRequest.ProtoReflect.Descriptor instead.
func (*ProjectDeleteRequest) Descriptor() ([]byte, []int) {
	return file_pb_robots_proto_rawDescGZIP(), []int{5}
}

func (x *ProjectDeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_pb_robots_proto protoreflect.FileDescriptor

const file_pb_robots_proto_rawDesc = "" +
	"\n" +
	"\x0fpb/robots.proto\x12\x06robots\"\a\n" +
	"\x05Empty\"Q\n" +
	"\fProjectModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\"\x16\n" +
	"\x14ProjectGetAllRequest\"#\n" +
	"\x11ProjectGetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"*\n" +
	"\x14ProjectCreateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"&\n" +
	"\x14ProjectDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\x85\x02\n" +
	"\x0eProjectService\x12@\n" +
	"\x06GetAll\x12\x1c.robots.ProjectGetAllRequest\x1a\x14.robots.ProjectModel\"\x000\x01\x128\n" +
	"\x03Get\x12\x19.robots.ProjectGetRequest\x1a\x14.robots.ProjectModel\"\x00\x12>\n" +
	"\x06Create\x12\x1c.robots.ProjectCreateRequest\x1a\x14.robots.ProjectModel\"\x00\x127\n" +
	"\x06Delete\x12\x1c.robots.ProjectDeleteRequest\x1a\r.robots.Empty\"\x00B\x11Z\x0fgenproto/robotsb\x06proto3"

var (
	file_pb_robots_proto_rawDescOnce sync.Once
	file_pb_robots_proto_rawDescData []byte
)

func file_pb_robots_proto_rawDescGZIP() []byte {
	file_pb_robots_proto_rawDescOnce.Do(func() {
		file_pb_robots_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_robots_proto_rawDesc), len(file_pb_robots_proto_rawDesc)))
	})
	return file_pb_robots_proto_rawDescData
}

var file_pb_robots_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pb_robots_proto_goTypes = []any{
	(*Empty)(nil),                // 0: robots.Empty
	(*ProjectModel)(nil),         // 1: robots.ProjectModel
	(*ProjectGetAllRequest)(nil), // 2: robots.ProjectGetAllRequest
	(*ProjectGetRequest)(nil),    // 3: robots.ProjectGetRequest
	(*ProjectCreateRequest)(nil), // 4: robots.ProjectCreateRequest
	(*ProjectDeleteRequest)(nil), // 5: robots.ProjectDeleteRequest
}
var file_pb_robots_proto_depIdxs = []int32{
	2, // 0: robots.ProjectService.GetAll:input_type -> robots.ProjectGetAllRequest
	3, // 1: robots.ProjectService.Get:input_type -> robots.ProjectGetRequest
	4, // 2: robots.ProjectService.Create:input_type -> robots.ProjectCreateRequest
	5, // 3: robots.ProjectService.Delete:input_type -> robots.ProjectDeleteRequest
	1, // 4: robots.ProjectService.GetAll:output_type -> robots.ProjectModel
	1, // 5: robots.ProjectService.Get:output_type -> robots.ProjectModel
	1, // 6: robots.ProjectService.Create:output_type -> robots.ProjectModel
	0, // 7: robots.ProjectService.Delete:output_type -> robots.Empty
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_robots_proto_init() }
func file_pb_robots_proto_init() {
	if File_pb_robots_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_robots_proto_rawDesc), len(file_pb_robots_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_robots_proto_goTypes,
		DependencyIndexes: file_pb_robots_proto_depIdxs,
		MessageInfos:      file_pb_robots_proto_msgTypes,
	}.Build()
	File_pb_robots_proto = out.File
	file_pb_robots_proto_goTypes = nil
	file_pb_robots_proto_depIdxs = nil
}
