// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: project/project.proto

package project

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProjectModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectModel) Reset() {
	*x = ProjectModel{}
	mi := &file_project_project_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectModel) ProtoMessage() {}

func (x *ProjectModel) ProtoReflect() protoreflect.Message {
	mi := &file_project_project_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectModel.ProtoReflect.Descriptor instead.
func (*ProjectModel) Descriptor() ([]byte, []int) {
	return file_project_project_proto_rawDescGZIP(), []int{0}
}

func (x *ProjectModel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProjectModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProjectModel) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ProjectGetAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectGetAllRequest) Reset() {
	*x = ProjectGetAllRequest{}
	mi := &file_project_project_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectGetAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectGetAllRequest) ProtoMessage() {}

func (x *ProjectGetAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_project_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectGetAllRequest.ProtoReflect.Descriptor instead.
func (*ProjectGetAllRequest) Descriptor() ([]byte, []int) {
	return file_project_project_proto_rawDescGZIP(), []int{1}
}

type ProjectGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectGetRequest) Reset() {
	*x = ProjectGetRequest{}
	mi := &file_project_project_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectGetRequest) ProtoMessage() {}

func (x *ProjectGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_project_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectGetRequest.ProtoReflect.Descriptor instead.
func (*ProjectGetRequest) Descriptor() ([]byte, []int) {
	return file_project_project_proto_rawDescGZIP(), []int{2}
}

func (x *ProjectGetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ProjectCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectCreateRequest) Reset() {
	*x = ProjectCreateRequest{}
	mi := &file_project_project_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectCreateRequest) ProtoMessage() {}

func (x *ProjectCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_project_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectCreateRequest.ProtoReflect.Descriptor instead.
func (*ProjectCreateRequest) Descriptor() ([]byte, []int) {
	return file_project_project_proto_rawDescGZIP(), []int{3}
}

func (x *ProjectCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ProjectDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectDeleteRequest) Reset() {
	*x = ProjectDeleteRequest{}
	mi := &file_project_project_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectDeleteRequest) ProtoMessage() {}

func (x *ProjectDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_project_project_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectDeleteRequest.ProtoReflect.Descriptor instead.
func (*ProjectDeleteRequest) Descriptor() ([]byte, []int) {
	return file_project_project_proto_rawDescGZIP(), []int{4}
}

func (x *ProjectDeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_project_project_proto protoreflect.FileDescriptor

const file_project_project_proto_rawDesc = "" +
	"\n" +
	"\x15project/project.proto\x12\aproject\x1a\x1bgoogle/protobuf/empty.proto\"Q\n" +
	"\fProjectModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\"\x16\n" +
	"\x14ProjectGetAllRequest\"#\n" +
	"\x11ProjectGetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"*\n" +
	"\x14ProjectCreateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"&\n" +
	"\x14ProjectDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\x8e\x02\n" +
	"\aProject\x12B\n" +
	"\x06GetAll\x12\x1d.project.ProjectGetAllRequest\x1a\x15.project.ProjectModel\"\x000\x01\x12:\n" +
	"\x03Get\x12\x1a.project.ProjectGetRequest\x1a\x15.project.ProjectModel\"\x00\x12@\n" +
	"\x06Create\x12\x1d.project.ProjectCreateRequest\x1a\x15.project.ProjectModel\"\x00\x12A\n" +
	"\x06Delete\x12\x1d.project.ProjectDeleteRequest\x1a\x16.google.protobuf.Empty\"\x00B$Z\"github.com/MatusBoa/robots/projectb\x06proto3"

var (
	file_project_project_proto_rawDescOnce sync.Once
	file_project_project_proto_rawDescData []byte
)

func file_project_project_proto_rawDescGZIP() []byte {
	file_project_project_proto_rawDescOnce.Do(func() {
		file_project_project_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_project_project_proto_rawDesc), len(file_project_project_proto_rawDesc)))
	})
	return file_project_project_proto_rawDescData
}

var file_project_project_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_project_project_proto_goTypes = []any{
	(*ProjectModel)(nil),         // 0: project.ProjectModel
	(*ProjectGetAllRequest)(nil), // 1: project.ProjectGetAllRequest
	(*ProjectGetRequest)(nil),    // 2: project.ProjectGetRequest
	(*ProjectCreateRequest)(nil), // 3: project.ProjectCreateRequest
	(*ProjectDeleteRequest)(nil), // 4: project.ProjectDeleteRequest
	(*emptypb.Empty)(nil),        // 5: google.protobuf.Empty
}
var file_project_project_proto_depIdxs = []int32{
	1, // 0: project.Project.GetAll:input_type -> project.ProjectGetAllRequest
	2, // 1: project.Project.Get:input_type -> project.ProjectGetRequest
	3, // 2: project.Project.Create:input_type -> project.ProjectCreateRequest
	4, // 3: project.Project.Delete:input_type -> project.ProjectDeleteRequest
	0, // 4: project.Project.GetAll:output_type -> project.ProjectModel
	0, // 5: project.Project.Get:output_type -> project.ProjectModel
	0, // 6: project.Project.Create:output_type -> project.ProjectModel
	5, // 7: project.Project.Delete:output_type -> google.protobuf.Empty
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_project_project_proto_init() }
func file_project_project_proto_init() {
	if File_project_project_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_project_project_proto_rawDesc), len(file_project_project_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_project_project_proto_goTypes,
		DependencyIndexes: file_project_project_proto_depIdxs,
		MessageInfos:      file_project_project_proto_msgTypes,
	}.Build()
	File_project_project_proto = out.File
	file_project_project_proto_goTypes = nil
	file_project_project_proto_depIdxs = nil
}
